name: Generate Keystore

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v6.0.0
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Generate keystore
        run: |
          keytool -genkeypair -v \
            -keystore android_keystore.jks \
            -alias "${{ secrets.APP_KEYSTORE_ALIAS }}" \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -storepass "${{ secrets.APP_KEYSTORE_PASSWORD }}" \
            -keypass "${{ secrets.APP_KEY_PASSWORD }}" \
            -dname "CN=UC VPN, OU=, O=, L=, S=, C=IR"
          base64 -w0 android_keystore.jks > android_keystore_base64.txt

      - name: Upload keystore base64
        uses: actions/upload-artifact@v7
        with:
          name: keystore-base64
          path: android_keystore_base64.txt
